using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class IdleCamera : MonoBehaviour
{
    public float targetSize = 5f; // Tamanho desejado da c창mera
    public float resizeSpeed = 2f; // Velocidade de ajuste do tamanho
    public float defaultSize = 3f; // Tamanho padr찾o da c창mera
    private Camera cameraComponent;
    private float currentSize;

    void Start()
    {
        cameraComponent = GetComponent<Camera>();
        currentSize = cameraComponent.orthographicSize;
    }

    void Update()
    {
        if (gameObject.GetComponent<CameraFollow>().targetIdle)
        {
        // Interpolar suavemente entre o tamanho atual e o tamanho desejado
        currentSize = Mathf.Lerp(currentSize, targetSize, resizeSpeed * Time.deltaTime);

        // Definir o tamanho da c창mera
        cameraComponent.orthographicSize = currentSize;
        }
        else{
            currentSize = Mathf.Lerp(currentSize, defaultSize, resizeSpeed * Time.deltaTime);
            cameraComponent.orthographicSize = currentSize;
        }
    }
}